"""Engineering Intelligence: turning retrieved evidence into engineering
conclusions a maintainer can act on and check.

Phases 1 and 2 built retrieval -- code, commits, pull requests, resolved
issues. This phase adds no new source. It reasons over what is already
retrieved to answer the questions that actually block a maintainer: what
probably broke, why, what to look at first, how bad it is, and whether
this has happened before.

The design constraint that shapes everything: **a conclusion that can't
name its evidence is not allowed to exist.** `Claim` enforces it in its
constructor (evidence.py), the analyzers only ever build claims from
retrieved chunks (analysis.py), and the renderer writes every factual
reference itself rather than letting a model produce one (report.py). The
result is that GHIC can be *wrong* -- a correlation can mislead -- but it
cannot be *unfounded*, and a maintainer can check any statement in seconds.

Two deliberate refusals, documented where they're implemented:

  **No LLM in the analysis path.** A root cause generated by a language
  model is a fluent guess whose confidence tracks its phrasing. One derived
  from "this commit modified the file this issue names, three days before
  it was filed" is a lead someone can verify. The LLM keeps its existing
  job -- readable prose -- and the findings are computed where they can be
  tested.

  **No uncalibrated numbers dressed as measurements.** Component health and
  repository risk are heuristic indices with published formulas over
  measured counts, withheld entirely below a minimum sample size, and never
  described as probabilities. This follows PRIORITY_CARD.md and
  SEVERITY_CARD.md, which refused to ship exactly this kind of number when
  it couldn't be validated.

See models/ENGINEERING_INTELLIGENCE_CARD.md.
"""
from .analysis import (
    EngineeringAnalysis,
    EngineeringAnalyzer,
    extract_identifiers,
    parse_releases,
)
from .clustering import IssueCluster, cluster_history, classify_relationship
from .components import (
    ComponentAnalyzer,
    ComponentStats,
    component_for_path,
    health_score,
    is_regression_text,
    summarize_repository,
)
from .evidence import (
    Claim,
    ClaimStatus,
    Confidence,
    Evidence,
    EvidenceKind,
    Finding,
    confidence_from_support,
    hedge,
)
from .report import (
    render_attribution_note,
    render_engineering_sections,
    render_finding,
    render_investigation_plan,
    render_timeline,
)

__all__ = [
    # Evidence spine
    "Evidence",
    "EvidenceKind",
    "Claim",
    "ClaimStatus",
    "Confidence",
    "Finding",
    "confidence_from_support",
    "hedge",
    # Analysis
    "EngineeringAnalyzer",
    "EngineeringAnalysis",
    "extract_identifiers",
    "parse_releases",
    # Components
    "ComponentAnalyzer",
    "ComponentStats",
    "component_for_path",
    "health_score",
    "is_regression_text",
    "summarize_repository",
    # Clustering
    "cluster_history",
    "classify_relationship",
    "IssueCluster",
    # Rendering
    "render_engineering_sections",
    "render_finding",
    "render_investigation_plan",
    "render_timeline",
    "render_attribution_note",
]
