"""Engineering analysis: root cause hypotheses, timelines, regression and
release correlation, impact, and an investigation plan.

Everything here is **deterministic and derived from retrieved evidence**.
No LLM call happens in this module, deliberately: a root-cause hypothesis
generated by a language model is a fluent guess whose confidence tracks its
phrasing, while one derived from "this commit modified the file this issue
names, three days before it was filed" is a correlation a maintainer can
check in ten seconds. The LLM's job (in ghic/llm/) stays what it was --
turning findings into readable prose -- and the findings themselves are
computed here where they can be tested.

The core operation is **overlap**: an issue names files or symbols; commits
touched files; past issues were closed by commits touching files. Where
those overlap, there is a lead. Where they don't, this module says nothing
rather than reaching for the next-best correlation, which is the same
similarity-floor discipline Phase 1 established.

Nothing here asserts causation. A commit that touched the relevant file
shortly before an issue was filed is *evidence worth checking*, and the
vocabulary throughout ("possibly", "likely", "appears related") is applied
in code via `evidence.hedge()` rather than left to a prompt that a later
edit could weaken.
"""
from __future__ import annotations

import re
import time
from dataclasses import dataclass, field
from typing import Any

from .. import utils
from .components import component_for_path, is_regression_text
from .evidence import (
    Claim,
    ClaimStatus,
    Confidence,
    Evidence,
    EvidenceKind,
    Finding,
    confidence_from_support,
    hedge,
)

logger = utils.get_logger(__name__)

# A commit within this window before the issue was filed is temporally
# plausible as a cause. Wide enough to cover a release cycle, narrow enough
# that "some commit in the last year" doesn't qualify as a lead.
SUSPECT_WINDOW_DAYS = 45

# An issue filed within this window after a release is worth flagging as a
# possible regression window.
RELEASE_WINDOW_DAYS = 14

_DAY = 86400.0

_IDENTIFIER_RE = re.compile(
    r"`([^`\n]{2,60})`"
    r"|\b([\w./-]+\.(?:py|js|jsx|ts|tsx|go|rs|java|cs))\b"
    r"|\b([a-z][a-z0-9]*(?:_[a-z0-9]+)+)\b"
    r"|\b([a-z]+(?:[A-Z][a-z0-9]+)+)\b"
)


@dataclass
class EngineeringAnalysis:
    """Everything Phase 3 derived for one issue.

    Findings are optional by construction: a repository with no indexed
    history produces an analysis with no findings, and the report renders
    nothing rather than empty headings.
    """
    repo: str
    issue_number: int = 0
    root_cause: Finding | None = None
    regression: Finding | None = None
    impact: Finding | None = None
    timeline: list[dict[str, Any]] = field(default_factory=list)
    investigation_plan: list[Claim] = field(default_factory=list)
    components: list[str] = field(default_factory=list)
    related_issues: list[Evidence] = field(default_factory=list)
    related_commits: list[Evidence] = field(default_factory=list)
    related_pull_requests: list[Evidence] = field(default_factory=list)
    recurrence: Finding | None = None

    @property
    def is_empty(self) -> bool:
        return not any([
            self.root_cause, self.regression, self.impact, self.recurrence,
            self.investigation_plan, self.timeline,
        ])

    def as_dict(self) -> dict[str, Any]:
        return {
            "repo": self.repo,
            "issue_number": self.issue_number,
            "components": self.components,
            "root_cause": self.root_cause.as_dict() if self.root_cause else None,
            "regression": self.regression.as_dict() if self.regression else None,
            "impact": self.impact.as_dict() if self.impact else None,
            "recurrence": self.recurrence.as_dict() if self.recurrence else None,
            "timeline": self.timeline,
            "investigation_plan": [c.as_dict() for c in self.investigation_plan],
            "related_issues": [e.as_dict() for e in self.related_issues],
            "related_commits": [e.as_dict() for e in self.related_commits],
            "related_pull_requests": [e.as_dict() for e in self.related_pull_requests],
        }


def extract_identifiers(text: str) -> set[str]:
    """Code-shaped tokens an issue mentions: filenames, functions, symbols."""
    found: set[str] = set()
    for groups in _IDENTIFIER_RE.findall(text or ""):
        for value in groups:
            token = (value or "").strip("`").strip()
            if len(token) > 2:
                found.add(token.lower())
    return found


class EngineeringAnalyzer:
    """Derives findings from a `RepositoryContext` plus the issue text.

    Constructed with tunables rather than reading config directly, so a
    test can narrow a window without building a config object.
    """

    def __init__(
        self,
        *,
        suspect_window_days: int = SUSPECT_WINDOW_DAYS,
        release_window_days: int = RELEASE_WINDOW_DAYS,
        max_plan_steps: int = 6,
    ) -> None:
        self.suspect_window_days = suspect_window_days
        self.release_window_days = release_window_days
        self.max_plan_steps = max_plan_steps

    def analyze(
        self,
        repo: str,
        title: str,
        body: str,
        repository_context: Any,
        *,
        issue_number: int = 0,
        issue_created_at: float | None = None,
        releases: list[dict[str, Any]] | None = None,
    ) -> EngineeringAnalysis:
        """Never raises. An analysis it can't support is an empty one."""
        analysis = EngineeringAnalysis(repo=repo, issue_number=issue_number)
        if repository_context is None or getattr(repository_context, "is_empty", True):
            return analysis

        try:
            return self._analyze(
                analysis, title, body, repository_context,
                issue_created_at or time.time(), releases or [],
            )
        except Exception as e:
            logger.warning("engineering analysis failed for %s#%s: %s", repo, issue_number, e)
            return EngineeringAnalysis(repo=repo, issue_number=issue_number)

    def _analyze(
        self,
        analysis: EngineeringAnalysis,
        title: str,
        body: str,
        context: Any,
        issue_time: float,
        releases: list[dict[str, Any]],
    ) -> EngineeringAnalysis:
        code = list(getattr(context, "code_chunks", []))
        history = list(getattr(context, "history_chunks", []))
        commits = [rc for rc in history if rc.chunk.kind == "commit"]
        issues = [rc for rc in history if rc.chunk.kind == "issue"]
        pulls = [rc for rc in history if rc.chunk.kind == "pull_request"]

        issue_text = f"{title}\n{body}"
        mentioned = extract_identifiers(issue_text)

        analysis.components = sorted({
            component_for_path(rc.chunk.path) for rc in code
        } - {""})
        analysis.related_commits = [Evidence.from_chunk(rc.chunk) for rc in commits]
        analysis.related_issues = [Evidence.from_chunk(rc.chunk) for rc in issues]
        analysis.related_pull_requests = [Evidence.from_chunk(rc.chunk) for rc in pulls]

        analysis.root_cause = self._root_cause(code, commits, mentioned, issue_time, issue_text)
        analysis.regression = self._regression(issue_text, commits, releases, issue_time)
        analysis.recurrence = self._recurrence(issues, analysis.components)
        analysis.impact = self._impact(code, issues, analysis.components)
        analysis.timeline = self._timeline(commits, issues, pulls, releases, issue_time)
        analysis.investigation_plan = self._plan(code, commits, issues, analysis, issue_text)
        return analysis

    # -- Feature 1: root cause -------------------------------------------
    def _root_cause(
        self, code: list[Any], commits: list[Any], mentioned: set[str],
        issue_time: float, issue_text: str,
    ) -> Finding | None:
        """Commits that recently touched the code this issue is about.

        Three independent signals, each of which must be *observed*:
        temporal proximity, file overlap with the retrieved code, and the
        issue naming an identifier the commit touched. A hypothesis needs
        at least the first two -- a recent commit somewhere unrelated is
        not a lead, and neither is an old commit in the right file.
        """
        if not commits:
            return None

        retrieved_files = {rc.chunk.path for rc in code}
        retrieved_components = {component_for_path(p) for p in retrieved_files} - {""}
        window = self.suspect_window_days * _DAY

        claims: list[Claim] = []
        for rc in commits:
            chunk = rc.chunk
            age = issue_time - chunk.timestamp
            if chunk.timestamp <= 0 or age < 0 or age > window:
                continue

            touched = _commit_paths(chunk.text)
            overlapping = [p for p in touched if p in retrieved_files]
            component_overlap = {component_for_path(p) for p in touched} & retrieved_components
            if not overlapping and not component_overlap:
                continue

            names_identifier = any(
                token in f"{chunk.symbol} {chunk.text}".lower() for token in mentioned
            ) if mentioned else False

            support = 1                             # temporal proximity
            support += 1 if overlapping else 0      # exact file overlap
            support += 1 if names_identifier else 0
            confidence = confidence_from_support(
                distinct_sources=support,
                strong_signal=bool(overlapping) and names_identifier,
            )

            where = overlapping[0] if overlapping else ", ".join(sorted(component_overlap)[:2])
            claims.append(Claim(
                statement=(
                    f"Commit `{chunk.reference}` ({chunk.symbol.strip()[:80]}) modified "
                    f"`{where}` {_ago(age)} this issue was filed, and {hedge(confidence)} "
                    "related to the reported behaviour."
                ),
                status=ClaimStatus.INFERRED,
                confidence=confidence,
                evidence=[
                    Evidence.from_chunk(chunk),
                    *[Evidence(kind=EvidenceKind.CODE, reference=p, detail="modified by this commit")
                      for p in overlapping[:2]],
                ],
            ))

        if not claims:
            return None
        order = {Confidence.HIGH: 0, Confidence.MEDIUM: 1, Confidence.LOW: 2}
        claims.sort(key=lambda c: order[c.confidence])
        return Finding(
            title="Possible root cause",
            claims=claims[:3],
            summary=(
                "Changes that touched the relevant code shortly before this issue "
                "appeared. Correlation from the index, not a confirmed cause."
            ),
        )

    # -- Feature 5 + 11: regression and release windows -------------------
    def _regression(
        self, issue_text: str, commits: list[Any],
        releases: list[dict[str, Any]], issue_time: float,
    ) -> Finding | None:
        claims: list[Claim] = []

        # The reporter's own words are the strongest available signal, and
        # the only one that is *verified* rather than inferred.
        if is_regression_text(issue_text):
            quoted = _first_matching_sentence(issue_text)
            claims.append(Claim(
                statement=(
                    "The report states this previously worked, which characterises it "
                    "as a regression rather than a new defect."
                ),
                status=ClaimStatus.VERIFIED,
                confidence=Confidence.HIGH,
                evidence=[Evidence(
                    kind=EvidenceKind.ISSUE_TEXT, reference="issue body",
                    detail=quoted[:160],
                )],
            ))

        for release in releases:
            released_at = float(release.get("timestamp") or 0)
            if released_at <= 0 or issue_time < released_at:
                continue
            gap_days = (issue_time - released_at) / _DAY
            if gap_days > self.release_window_days:
                continue
            confidence = Confidence.MEDIUM if gap_days <= 3 else Confidence.LOW
            claims.append(Claim(
                statement=(
                    f"This issue was filed {gap_days:.1f} day(s) after release "
                    f"`{release.get('name')}`, placing it inside a plausible "
                    "regression window for that release."
                ),
                status=ClaimStatus.INFERRED,
                confidence=confidence,
                evidence=[Evidence(
                    kind=EvidenceKind.RELEASE, reference=str(release.get("name")),
                    detail="release date from repository tags", timestamp=released_at,
                )],
            ))

        regression_commits = [
            rc for rc in commits
            if is_regression_text(f"{rc.chunk.symbol} {rc.chunk.text}")
        ]
        if regression_commits:
            chunk = regression_commits[0].chunk
            claims.append(Claim(
                statement=(
                    f"A related commit (`{chunk.reference}`) is itself described as fixing a "
                    "regression, suggesting this area has regressed before."
                ),
                status=ClaimStatus.VERIFIED,
                confidence=Confidence.MEDIUM,
                evidence=[Evidence.from_chunk(chunk)],
            ))

        if not claims:
            return None
        return Finding(
            title="Regression signals", claims=claims,
            summary="Evidence that this is a re-break rather than a new defect.",
        )

    # -- Feature 3 (recurrence half) --------------------------------------
    def _recurrence(self, issues: list[Any], components: list[str]) -> Finding | None:
        """Whether this area has produced similar issues before.

        The clustering half of duplicate intelligence lives in
        clustering.py; this is the per-issue readout: two or more
        previously-resolved issues retrieved for the same area is a
        recurring problem, and saying so is more useful than listing them
        individually.
        """
        if len(issues) < 2:
            return None
        evidence = [Evidence.from_chunk(rc.chunk) for rc in issues[:4]]
        where = f" in `{components[0]}`" if components else ""
        return Finding(
            title="Recurring problem",
            claims=[Claim(
                statement=(
                    f"{len(issues)} previously-closed issues{where} resemble this report, "
                    "which suggests a recurring problem rather than an isolated one."
                ),
                status=ClaimStatus.INFERRED,
                confidence=confidence_from_support(distinct_sources=min(3, len(issues))),
                evidence=evidence,
            )],
        )

    # -- Feature 6: impact -------------------------------------------------
    def _impact(
        self, code: list[Any], issues: list[Any], components: list[str]
    ) -> Finding | None:
        """Impact inferred only from what the index shows.

        Deliberately narrow. "Customer impact" and "business risk" are not
        derivable from a repository -- a codebase does not know who its
        users are -- so this reports engineering-side impact: which
        components are implicated, and whether the area has a history of
        problems. The LLM layer already produces a grounded
        business-impact read from the issue's own text (Phase 1.5); this
        does not duplicate or contradict it.
        """
        claims: list[Claim] = []

        if components:
            file_evidence = [
                Evidence(kind=EvidenceKind.CODE, reference=rc.chunk.path,
                         detail=rc.chunk.qualified_symbol or "")
                for rc in code[:3]
            ]
            if file_evidence:
                claims.append(Claim(
                    statement=(
                        "Affected component(s): " + ", ".join(f"`{c}`" for c in components[:3])
                        + "."
                    ),
                    status=ClaimStatus.VERIFIED,
                    confidence=Confidence.MEDIUM,
                    evidence=file_evidence,
                ))

        if len(issues) >= 3:
            claims.append(Claim(
                statement=(
                    f"This area accounts for {len(issues)} prior resolved issues in the index, "
                    "so a fix here may affect behaviour several past reports depended on."
                ),
                status=ClaimStatus.INFERRED,
                confidence=Confidence.LOW,
                evidence=[Evidence.from_chunk(rc.chunk) for rc in issues[:3]],
            ))

        if not claims:
            return None
        return Finding(
            title="Engineering impact", claims=claims,
            summary="Scope inferred from the indexed code and history only.",
        )

    # -- Feature 7: timeline ----------------------------------------------
    def _timeline(
        self, commits: list[Any], issues: list[Any], pulls: list[Any],
        releases: list[dict[str, Any]], issue_time: float,
    ) -> list[dict[str, Any]]:
        """Retrieved artifacts in chronological order.

        Pure fact -- every entry is a dated artifact from the index, with
        this issue anchored at the end. Its value is that a maintainer can
        see "release, then commit, then three similar issues, then this
        one" at a glance, which no individual finding conveys.
        """
        events: list[dict[str, Any]] = []
        for rc in commits:
            if rc.chunk.timestamp:
                events.append({
                    "kind": "commit", "reference": rc.chunk.reference,
                    "label": rc.chunk.symbol.strip()[:100], "timestamp": rc.chunk.timestamp,
                })
        for rc in issues + pulls:
            if rc.chunk.timestamp:
                events.append({
                    "kind": rc.chunk.kind, "reference": rc.chunk.reference,
                    "label": rc.chunk.symbol.strip()[:100], "timestamp": rc.chunk.timestamp,
                    "url": rc.chunk.url,
                })
        for release in releases:
            if release.get("timestamp"):
                events.append({
                    "kind": "release", "reference": str(release.get("name")),
                    "label": "release", "timestamp": float(release["timestamp"]),
                })

        events = [e for e in events if e["timestamp"] <= issue_time + _DAY]
        events.sort(key=lambda e: e["timestamp"])
        events = events[-8:]
        events.append({
            "kind": "current_issue", "reference": "this issue",
            "label": "reported", "timestamp": issue_time,
        })
        return events

    # -- Feature 2: investigation plan ------------------------------------
    def _plan(
        self, code: list[Any], commits: list[Any], issues: list[Any],
        analysis: EngineeringAnalysis, issue_text: str,
    ) -> list[Claim]:
        """An ordered checklist where every step names a real artifact.

        Ordered by what a maintainer would actually do first: read the
        implicated code, check the change that may have caused it, look at
        how this was handled before, then reproduce. Steps that have no
        evidence to name are omitted rather than padded with generic
        advice -- "write a test" is not an investigation step, it's filler.
        """
        steps: list[Claim] = []

        for rc in code[:2]:
            chunk = rc.chunk
            target = chunk.qualified_symbol or chunk.path
            steps.append(Claim(
                statement=(
                    f"Review `{target}` in `{chunk.path}` "
                    f"(lines {chunk.start_line}-{chunk.end_line}) — the retrieved code "
                    "most similar to this report."
                ),
                status=ClaimStatus.VERIFIED,
                confidence=Confidence.MEDIUM,
                evidence=[Evidence.from_chunk(chunk)],
            ))

        if analysis.root_cause and analysis.root_cause.claims:
            top = analysis.root_cause.claims[0]
            commit_ref = next(
                (e.reference for e in top.evidence if e.kind is EvidenceKind.COMMIT), ""
            )
            if commit_ref:
                steps.append(Claim(
                    statement=(
                        f"Compare against commit `{commit_ref}` — it changed this area "
                        "shortly before the issue appeared."
                    ),
                    status=ClaimStatus.INFERRED,
                    confidence=top.confidence,
                    evidence=top.evidence[:2],
                ))

        if is_regression_text(issue_text) and commits:
            steps.append(Claim(
                statement=(
                    "Bisect between the last known-good version named in the report and "
                    "the current one — the report describes previously working behaviour."
                ),
                status=ClaimStatus.INFERRED,
                confidence=Confidence.MEDIUM,
                evidence=[Evidence(
                    kind=EvidenceKind.ISSUE_TEXT, reference="issue body",
                    detail=_first_matching_sentence(issue_text)[:160],
                )],
            ))

        if issues:
            chunk = issues[0].chunk
            steps.append(Claim(
                statement=(
                    f"Check how {chunk.reference} was resolved — it is the closest "
                    "previously-closed issue to this report."
                ),
                status=ClaimStatus.INFERRED,
                confidence=Confidence.MEDIUM,
                evidence=[Evidence.from_chunk(chunk)],
            ))

        return steps[:self.max_plan_steps]


def _ago(seconds: float) -> str:
    """Human phrasing for a gap. "0 day(s) before" reads as a bug even when
    the arithmetic is right."""
    days = seconds / _DAY
    if days < 1:
        return "less than a day before"
    if days < 2:
        return "1 day before"
    return f"{int(days)} days before"


def _commit_paths(text: str) -> list[str]:
    marker = "Files changed:"
    if marker not in (text or ""):
        return []
    tail = text.split(marker, 1)[1].split("\n", 1)[0]
    return [p.strip() for p in tail.split(",") if p.strip() and not p.strip().startswith("(")]


def _first_matching_sentence(text: str) -> str:
    """The sentence that made `is_regression_text` true, for quoting.

    Quoting the reporter's own words rather than paraphrasing keeps the
    claim verifiable at a glance.
    """
    for sentence in re.split(r"(?<=[.!?])\s+|\n", text or ""):
        if is_regression_text(sentence):
            return sentence.strip()
    return (text or "").strip()[:160]


def parse_releases(tag_output: str) -> list[dict[str, Any]]:
    """`git tag` output (name + ISO date, tab separated) -> release records.

    Kept here rather than in the git layer so release correlation is
    testable without a repository, and so a deployment that gets releases
    from the GitHub API can feed the same shape.
    """
    releases: list[dict[str, Any]] = []
    for line in (tag_output or "").split("\n"):
        line = line.strip()
        if not line:
            continue
        parts = line.split("\t")
        if len(parts) < 2:
            continue
        name, iso = parts[0].strip(), parts[1].strip()
        from ..repository_intelligence.sources import _parse_timestamp

        timestamp = _parse_timestamp(iso)
        if name and timestamp:
            releases.append({"name": name, "timestamp": timestamp})
    releases.sort(key=lambda r: -r["timestamp"])
    return releases[:50]
