"""Suggestion generators: fix plans, test plans, checklists, labels,
assignees, and duplicate workflow.

All deterministic, all derived from evidence Phases 1-3 already produced.
The Phase 3 reasoning holds: a suggestion generated by a language model is
a fluent guess, while one derived from "this function is what the retriever
returned and this commit last changed it" is checkable.

**Fix plans are plans, not patches.** The spec says so, and it's the right
call independently: generating a diff for a codebase the tool has only
seen fragments of produces code that looks right and doesn't compile, and
reviewing a wrong patch costs more than writing a right one. What saves a
maintainer time is knowing *which function*, *why*, and *what to verify* --
so that is what this produces.
"""
from __future__ import annotations

import re
from typing import Any

from .. import utils
from ..engineering_intelligence.clustering import (
    DUPLICATE,
    REGRESSION_FAMILY,
    classify_relationship,
)
from ..engineering_intelligence.components import component_for_path, is_regression_text
from ..engineering_intelligence.evidence import (
    Confidence,
    Evidence,
    EvidenceKind,
)
from .models import ActionKind, Recommendation

logger = utils.get_logger(__name__)

# Evidence-backed label rules. Each label needs a *reason a maintainer can
# check*, which is why these are keyed on observable signals -- a marker in
# the issue text, a path in the retrieved code -- rather than on a model's
# opinion of the issue's vibe.
_TEXT_LABEL_RULES: tuple[tuple[str, tuple[str, ...], str], ...] = (
    ("security", ("vulnerability", "exploit", "cve-", "xss", "csrf", "sql injection",
                  "rce", "privilege escalation", "auth bypass", "security"),
     "the report uses security-incident vocabulary"),
    ("performance", ("slow", "latency", "timeout", "memory leak", "cpu", "throughput",
                     "performance", "hangs", "freezes", "n+1"),
     "the report describes a performance symptom"),
    ("documentation", ("docs", "documentation", "readme", "typo in the doc",
                       "unclear instructions"),
     "the report is about documentation rather than behaviour"),
    ("api", ("endpoint", "rest api", "graphql", "http 4", "http 5", "status code",
             "request body", "response body"),
     "the report concerns an API surface"),
    ("database", ("migration", "postgres", "mysql", "sqlite", "mongodb", "query plan",
                  "deadlock", "transaction"),
     "the report mentions database concerns"),
)

# Path-based labels. Stronger evidence than text: the retriever actually
# returned a file under this path.
_PATH_LABEL_RULES: tuple[tuple[str, tuple[str, ...], str], ...] = (
    ("frontend", ("/components/", "/pages/", "/views/", "/ui/", "/styles/",
                  ".tsx", ".jsx", ".vue", ".svelte", ".css"),
     "retrieved code lives in a frontend path"),
    ("backend", ("/api/", "/server/", "/service/", "/handlers/", "/controllers/",
                 "/routes/"),
     "retrieved code lives in a backend path"),
    ("database", ("/models/", "/migrations/", "/schema/", "/repositories/"),
     "retrieved code lives in a data-layer path"),
)

# Phrases that indicate the reporter gave enough to act on. Their absence
# is what justifies `needs-reproduction`.
_REPRO_MARKERS = (
    "steps to reproduce", "reproduce", "repro", "traceback", "stack trace",
    "expected behaviour", "expected behavior", "actual behaviour",
    "actual behavior", "```", "minimal example",
)

_COMMIT_AUTHOR_RE = re.compile(r"^Commit\s+\S+\s+by\s+(.+)$", re.MULTILINE)


def _issue_evidence(quote: str) -> Evidence:
    return Evidence(kind=EvidenceKind.ISSUE_TEXT, reference="issue body",
                    detail=quote[:160])


# ---------------------------------------------------------------------------
# Feature 1: fix plan
# ---------------------------------------------------------------------------
def build_fix_plan(analysis: Any, context: Any, *, stamp: dict[str, Any]) -> list[Recommendation]:
    """An implementation plan: which functions, why, and what to watch.

    Gated on the analysis actually having a root-cause hypothesis. Without
    one there is no evidence-backed opinion about *what to change*, and
    "review the code" is not a fix plan -- it's the absence of one dressed
    up as advice.
    """
    if analysis is None or not getattr(analysis, "root_cause", None):
        return []

    code = list(getattr(context, "code_chunks", []))
    if not code:
        return []

    top = analysis.root_cause.claims[0]
    recommendations: list[Recommendation] = []

    for retrieved in code[:2]:
        chunk = retrieved.chunk
        target = chunk.qualified_symbol or chunk.path
        recommendations.append(Recommendation(
            kind=ActionKind.REVIEW,
            title=f"Change candidate: `{target}`",
            detail=(
                f"`{chunk.path}` lines {chunk.start_line}-{chunk.end_line}. This is the "
                "retrieved code closest to the report, and the change most likely to be "
                "needed is here. Confirm the behaviour against the issue before editing."
            ),
            confidence=top.confidence,
            reason=(
                "retrieved as the most similar code to the issue text, and named by the "
                "root-cause hypothesis"
            ),
            evidence=[Evidence.from_chunk(chunk), *top.evidence[:1]],
            **stamp,
        ))

    commit_evidence = [e for e in top.evidence if e.kind is EvidenceKind.COMMIT]
    if commit_evidence:
        recommendations.append(Recommendation(
            kind=ActionKind.INVESTIGATE,
            title=f"Compare against commit `{commit_evidence[0].reference}`",
            detail=(
                "This change touched the same area shortly before the issue was filed. "
                "Diff it against the current state to see whether the reported behaviour "
                "was introduced here — if so, the fix may be a narrow correction to that "
                "change rather than new code."
            ),
            confidence=top.confidence,
            reason="temporal and file overlap with the reported symptom",
            evidence=commit_evidence[:2],
            **stamp,
        ))

    return recommendations


# ---------------------------------------------------------------------------
# Feature 3: test plan
# ---------------------------------------------------------------------------
def build_test_plan(
    analysis: Any, context: Any, title: str, body: str, *, stamp: dict[str, Any]
) -> list[Recommendation]:
    """Which tests should exist, and why -- not test code.

    Naming the function to cover and the condition to cover it under is the
    part a maintainer can't get from the issue alone. Writing the test body
    is the part they're faster at than any generator working from
    fragments.
    """
    code = list(getattr(context, "code_chunks", []))
    if not code:
        return []

    issue_text = f"{title}\n{body}"
    recommendations: list[Recommendation] = []
    chunk = code[0].chunk
    target = chunk.qualified_symbol or chunk.path

    recommendations.append(Recommendation(
        kind=ActionKind.TEST,
        title=f"Unit test for `{target}`",
        detail=(
            f"Cover the specific input described in the report against `{target}` "
            f"in `{chunk.path}`. A test that fails before the fix and passes after is "
            "what turns this issue into a permanent guarantee."
        ),
        confidence=Confidence.MEDIUM,
        reason="this is the code the retriever returned for the reported symptom",
        evidence=[Evidence.from_chunk(chunk)],
        **stamp,
    ))

    if is_regression_text(issue_text):
        recommendations.append(Recommendation(
            kind=ActionKind.TEST,
            title="Regression test pinning the previously-working behaviour",
            detail=(
                "The report states this used to work, so the behaviour has no test "
                "protecting it. Add one asserting the old behaviour explicitly, "
                "independently of the fix — otherwise the next refactor breaks it again."
            ),
            confidence=Confidence.HIGH,
            reason="the reporter describes previously-working behaviour",
            evidence=[_issue_evidence(_first_sentence_matching(issue_text))],
            **stamp,
        ))

    if getattr(analysis, "recurrence", None):
        recommendations.append(Recommendation(
            kind=ActionKind.TEST,
            title="Integration test across the recurring area",
            detail=(
                "This area has produced repeated issues, which usually means unit tests "
                "cover the pieces but not the path through them. An integration test "
                "over the whole flow is what catches the class of bug, not the instance."
            ),
            confidence=Confidence.MEDIUM,
            reason="multiple prior resolved issues retrieved for the same component",
            evidence=analysis.recurrence.claims[0].evidence[:2],
            **stamp,
        ))

    edge_cases = _edge_cases_in(issue_text)
    if edge_cases:
        recommendations.append(Recommendation(
            kind=ActionKind.TEST,
            title="Edge cases named in the report",
            detail="Cover: " + ", ".join(f"`{c}`" for c in edge_cases[:4]) + ".",
            confidence=Confidence.MEDIUM,
            reason="these specific conditions appear in the issue text",
            evidence=[_issue_evidence(", ".join(edge_cases[:4]))],
            **stamp,
        ))

    return recommendations


_EDGE_CASE_MARKERS = (
    "empty", "null", "none", "zero", "negative", "unicode", "utf-8", "latin-1",
    "large file", "concurrent", "timeout", "offline", "special character",
    "whitespace", "duplicate", "missing field", "malformed",
)


def _edge_cases_in(text: str) -> list[str]:
    lowered = (text or "").lower()
    return [marker for marker in _EDGE_CASE_MARKERS if marker in lowered]


def _first_sentence_matching(text: str) -> str:
    for sentence in re.split(r"(?<=[.!?])\s+|\n", text or ""):
        if is_regression_text(sentence):
            return sentence.strip()
    return (text or "")[:160]


# ---------------------------------------------------------------------------
# Feature 4: completion checklist
# ---------------------------------------------------------------------------
def build_checklist(
    analysis: Any, context: Any, title: str, body: str, *, stamp: dict[str, Any]
) -> list[Recommendation]:
    """A repository-specific checklist.

    Every item names something concrete from this repository. A generic
    checklist ("reproduce the issue, fix it, close it") is filler a
    maintainer skips; naming the file, the commit, and the version makes it
    worth reading.
    """
    issue_text = f"{title}\n{body}"
    code = list(getattr(context, "code_chunks", []))
    items: list[Recommendation] = []

    if not _has_reproduction(issue_text):
        items.append(Recommendation(
            kind=ActionKind.REQUEST_INFO,
            title="Ask for reproduction steps before investigating",
            detail=(
                "The report contains no steps, stack trace, or code block, so any "
                "investigation starts by guessing at the conditions."
            ),
            confidence=Confidence.HIGH,
            reason="no reproduction markers found in the issue body",
            evidence=[_issue_evidence((body or "(empty body)")[:160])],
            **stamp,
        ))
    else:
        items.append(Recommendation(
            kind=ActionKind.INVESTIGATE,
            title="Reproduce using the steps in the report",
            detail="The report includes reproduction detail; confirm it before changing code.",
            confidence=Confidence.HIGH,
            reason="reproduction markers present in the issue body",
            evidence=[_issue_evidence((body or "")[:160])],
            **stamp,
        ))

    if code:
        chunk = code[0].chunk
        items.append(Recommendation(
            kind=ActionKind.REVIEW,
            title=f"Review `{chunk.qualified_symbol or chunk.path}`",
            detail=f"`{chunk.path}` lines {chunk.start_line}-{chunk.end_line}.",
            confidence=Confidence.MEDIUM,
            reason="closest retrieved code to the reported symptom",
            evidence=[Evidence.from_chunk(chunk)],
            **stamp,
        ))

    if getattr(analysis, "root_cause", None):
        top = analysis.root_cause.claims[0]
        commits = [e for e in top.evidence if e.kind is EvidenceKind.COMMIT]
        if commits:
            items.append(Recommendation(
                kind=ActionKind.INVESTIGATE,
                title=f"Review commit `{commits[0].reference}`",
                detail="Changed this area shortly before the issue appeared.",
                confidence=top.confidence,
                reason="root-cause correlation",
                evidence=commits[:1],
                **stamp,
            ))

    if is_regression_text(issue_text):
        items.append(Recommendation(
            kind=ActionKind.INVESTIGATE,
            title="Confirm the affected version range",
            detail=(
                "The report names a previously-working version. Establish the exact "
                "range before fixing so the fix can be backported correctly."
            ),
            confidence=Confidence.HIGH,
            reason="the report describes a regression",
            evidence=[_issue_evidence(_first_sentence_matching(issue_text))],
            **stamp,
        ))

    return items


def _has_reproduction(text: str) -> bool:
    lowered = (text or "").lower()
    return any(marker in lowered for marker in _REPRO_MARKERS)


# ---------------------------------------------------------------------------
# Feature 6: smart labels
# ---------------------------------------------------------------------------
def build_label_suggestions(
    analysis: Any, context: Any, title: str, body: str, *, stamp: dict[str, Any]
) -> list[Recommendation]:
    """Labels with a checkable justification each.

    "Only recommend labels supported by evidence" is the whole design: each
    rule fires on an observable -- a phrase in the report, a path in the
    retrieved code, a Phase 3 finding -- and the reason field names it. A
    label GHIC can't justify is one it doesn't suggest.
    """
    issue_text = f"{title}\n{body}"
    lowered = issue_text.lower()
    suggestions: dict[str, Recommendation] = {}

    def add(label: str, reason: str, evidence: list[Evidence], confidence: Confidence) -> None:
        if label in suggestions:
            return
        suggestions[label] = Recommendation(
            kind=ActionKind.LABEL, title=label,
            detail=f"Suggested label `{label}`.",
            confidence=confidence, reason=reason, evidence=evidence, **stamp,
        )

    for label, markers, reason in _TEXT_LABEL_RULES:
        hit = next((m for m in markers if m in lowered), None)
        if hit:
            add(label, f"{reason} (matched \"{hit}\")",
                [_issue_evidence(_context_around(issue_text, hit))], Confidence.MEDIUM)

    for retrieved in list(getattr(context, "code_chunks", []))[:5]:
        path = retrieved.chunk.path.lower()
        for label, markers, reason in _PATH_LABEL_RULES:
            if any(m in path for m in markers):
                add(label, f"{reason} (`{retrieved.chunk.path}`)",
                    [Evidence.from_chunk(retrieved.chunk)], Confidence.MEDIUM)

    if is_regression_text(issue_text):
        add("regression", "the report states this previously worked",
            [_issue_evidence(_first_sentence_matching(issue_text))], Confidence.HIGH)

    if not _has_reproduction(issue_text):
        add("needs-reproduction",
            "no steps, stack trace, or code block found in the report",
            [_issue_evidence((body or "(empty body)")[:160])], Confidence.HIGH)

    # good-first-issue needs *positive* evidence of narrowness, not merely
    # the absence of complexity signals -- guessing wrong here sends a
    # newcomer into a hard problem, which is a worse outcome than silence.
    code = list(getattr(context, "code_chunks", []))
    if (
        code and len(code) <= 2
        and not is_regression_text(issue_text)
        and getattr(analysis, "recurrence", None) is None
        and _has_reproduction(issue_text)
    ):
        add("good-first-issue",
            "narrow scope: one or two files retrieved, reproduction included, "
            "and no regression or recurrence signals",
            [Evidence.from_chunk(code[0].chunk)], Confidence.LOW)

    return list(suggestions.values())


def _context_around(text: str, marker: str, width: int = 70) -> str:
    lowered = (text or "").lower()
    index = lowered.find(marker)
    if index < 0:
        return (text or "")[:width]
    start = max(0, index - width // 2)
    return (text or "")[start:start + width].strip()


# ---------------------------------------------------------------------------
# Feature 7: assignee recommendation
# ---------------------------------------------------------------------------
def build_assignee_suggestions(
    context: Any, *, stamp: dict[str, Any], limit: int = 3
) -> list[Recommendation]:
    """Maintainers who recently changed the implicated files.

    File expertise from commit authorship -- the most defensible signal
    available here, because it's a fact about who touched this code rather
    than an inference about who understands it. Never an assignment: the
    project already treats assignment as response-only (see
    `suggest_assignees` in settings.py), and this keeps that posture.
    """
    history = list(getattr(context, "history_chunks", []))
    code_paths = {rc.chunk.path for rc in getattr(context, "code_chunks", [])}
    if not history or not code_paths:
        return []

    components = {component_for_path(p) for p in code_paths} - {""}
    by_author: dict[str, list[Any]] = {}
    for retrieved in history:
        chunk = retrieved.chunk
        if chunk.kind != "commit":
            continue
        match = _COMMIT_AUTHOR_RE.search(chunk.text or "")
        if not match:
            continue
        author = match.group(1).strip()
        if not author or author.lower().endswith("[bot]"):
            continue
        touched = _commit_paths(chunk.text)
        overlaps = any(p in code_paths for p in touched) or bool(
            {component_for_path(p) for p in touched} & components
        )
        if overlaps:
            by_author.setdefault(author, []).append(chunk)

    ranked = sorted(by_author.items(), key=lambda kv: -len(kv[1]))[:limit]
    return [
        Recommendation(
            kind=ActionKind.ASSIGN,
            title=f"Possible reviewer: {author}",
            detail=(
                f"Authored {len(chunks)} retrieved commit(s) touching this area. "
                "A suggestion for a maintainer to consider — GHIC does not assign."
            ),
            confidence=Confidence.MEDIUM if len(chunks) > 1 else Confidence.LOW,
            reason="recent commit authorship in the implicated files",
            evidence=[Evidence.from_chunk(c) for c in chunks[:2]],
            **stamp,
        )
        for author, chunks in ranked
    ]


def _commit_paths(text: str) -> list[str]:
    marker = "Files changed:"
    if marker not in (text or ""):
        return []
    tail = text.split(marker, 1)[1].split("\n", 1)[0]
    return [p.strip() for p in tail.split(",") if p.strip() and not p.strip().startswith("(")]


# ---------------------------------------------------------------------------
# Feature 5: duplicate workflow
# ---------------------------------------------------------------------------
def build_duplicate_workflow(
    context: Any, title: str, body: str, *, stamp: dict[str, Any]
) -> list[Recommendation]:
    """What to do about a similar prior issue -- never the doing of it.

    `classify_relationship` (Phase 3) decides the relationship; this turns
    it into an action a maintainer takes. "Never auto-close" is not just
    unimplemented, it is unrepresentable: `ActionKind` has no CLOSE member.
    """
    history = [rc for rc in getattr(context, "history_chunks", []) if rc.chunk.kind == "issue"]
    if not history:
        return []

    issue_text = f"{title}\n{body}"
    issue_components = {
        component_for_path(rc.chunk.path) for rc in getattr(context, "code_chunks", [])
    } - {""}

    recommendations: list[Recommendation] = []
    for retrieved in history[:3]:
        chunk = retrieved.chunk
        relationship = classify_relationship(
            similarity=retrieved.score,
            issue_text=issue_text,
            candidate_text=f"{chunk.symbol} {chunk.text}",
            issue_components=issue_components,
            candidate_components=issue_components,
        )
        if relationship is None:
            continue

        if relationship == DUPLICATE:
            action = (
                f"Consider closing this as a duplicate of {chunk.reference} and linking "
                "them — after confirming the symptoms match. GHIC never closes issues."
            )
            confidence = Confidence.MEDIUM
        elif relationship == REGRESSION_FAMILY:
            action = (
                f"Keep this open and link it to {chunk.reference}. Both describe "
                "previously-working behaviour breaking, so this is a repeat break rather "
                "than a duplicate — closing it would hide that it happened twice."
            )
            confidence = Confidence.MEDIUM
        else:
            action = f"Cross-reference {chunk.reference}; related but not the same report."
            confidence = Confidence.LOW

        recommendations.append(Recommendation(
            kind=ActionKind.LINK,
            title=f"{relationship.title()}: {chunk.reference}",
            detail=action,
            confidence=confidence,
            reason=f"similarity {retrieved.score:.2f} and relationship classified as "
                   f"'{relationship}'",
            evidence=[Evidence.from_chunk(chunk)],
            **stamp,
        ))
    return recommendations
